In [43]:
import requests
import pandas as pd
import mysql.connector
from mysql.connector import errorcode

In [44]:
cnx = mysql.connector.connect(user="root", 
                              password = "25401229",
                              host = "127.0.0.1")

In [45]:
mycursor = cnx.cursor()

In [46]:
query = "USE Northwind"

Crear la conexión a la base de datos Northwind que devuelva un mensaje de error si algo no ocurre cómo debería.

In [47]:
try:
    mycursor.execute(query)
    print("conexion realizada")
except:
    print("error")

conexion realizada

Usando "information_schema" en la conexión a base de datos, extraer los nombres de las columnas de la tabla "customers" de la bases de datos "northwind".

In [64]:
info_schema = "SELECT * FROM customers"

In [65]:
mycursor.execute(info_schema)

In [66]:
datos = mycursor.fetchall()

In [67]:
df = pd.DataFrame(datos)

In [68]:
df

,0,1,2,3,4,5,6,7,8,9,10
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,NaN,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitucin 2222,Mxico D.F.,NaN,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquera,Antonio Moreno,Owner,Mataderos 2312,Mxico D.F.,NaN,05023,Mexico,(5) 555-3932,NaN
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbkp,Christina Berglund,Order Administrator,Berguvsvgen 8,Lule,NaN,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
...,...,...,...,...,...,...,...,...,...,...,...
88,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,NaN,90110,Finland,981-443655,981-443655
89,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,SP,08737-363,Brazil,(14) 555-8122,NaN
90,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115
91,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,NaN,21240,Finland,90-224 8858,90-224 8858
92,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,NaN,01-012,Poland,(26) 642-7012,(26) 642-7012

In [53]:
mycursor.description

[('CustomerID', 253, None, None, None, None, 0, 20483, 255),
 ('CompanyName', 253, None, None, None, None, 0, 20489, 255),
 ('ContactName', 253, None, None, None, None, 1, 0, 255),
 ('ContactTitle', 253, None, None, None, None, 1, 0, 255),
 ('Address', 253, None, None, None, None, 1, 0, 255),
 ('City', 253, None, None, None, None, 1, 16392, 255),
 ('Region', 253, None, None, None, None, 1, 16392, 255),
 ('PostalCode', 253, None, None, None, None, 1, 16392, 255),
 ('Country', 253, None, None, None, None, 1, 0, 255),
 ('Phone', 253, None, None, None, None, 1, 0, 255),
 ('Fax', 253, None, None, None, None, 1, 0, 255)]

In [54]:
lista = []
for c in mycursor.description:
    lista.append(c[0])
    print(c[0])
    print("----------------------------")

CustomerID
----------------------------
CompanyName
----------------------------
ContactName
----------------------------
ContactTitle
----------------------------
Address
----------------------------
City
----------------------------
Region
----------------------------
PostalCode
----------------------------
Country
----------------------------
Phone
----------------------------
Fax
----------------------------

Seleccionar todo de la tabla "customers" donde "city" sea "London" o "Seattle". Almacenar los resultados en una variable.

In [72]:
query_cities = """SELECT * 
                FROM customers
                WHERE city IN ('Seattle', 'London')"""

In [86]:
mycursor.execute(query_cities)

In [87]:
cities = mycursor.fetchall()

In [88]:
df_city = pd.DataFrame(cities, columns=lista)  #Ojo muy importante

In [89]:
df_city

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
1,BSBEV,B's Beverages,Victoria Ashworth,Sales Representative,Fauntleroy Circus,London,NaN,EC2 5NT,UK,(171) 555-1212,NaN
2,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,NaN,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,NaN,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,NaN,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
5,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,NaN,OX15 4NB,UK,(171) 555-1717,(171) 555-5646
6,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115

Muestra las 10 primeras filas del Dataframe y las 10 últimas.

In [90]:
df_city.head(10)

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
1,BSBEV,B's Beverages,Victoria Ashworth,Sales Representative,Fauntleroy Circus,London,NaN,EC2 5NT,UK,(171) 555-1212,NaN
2,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,NaN,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,NaN,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,NaN,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
5,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,NaN,OX15 4NB,UK,(171) 555-1717,(171) 555-5646
6,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115

In [91]:
df_city.tail(10)

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
1,BSBEV,B's Beverages,Victoria Ashworth,Sales Representative,Fauntleroy Circus,London,NaN,EC2 5NT,UK,(171) 555-1212,NaN
2,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,NaN,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,NaN,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,NaN,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
5,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,NaN,OX15 4NB,UK,(171) 555-1717,(171) 555-5646
6,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115

Mostrar 5 filas aleatorias del Dataframe.

In [93]:
df_city.sample(5)

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,NaN,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
6,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,NaN,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
5,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,NaN,OX15 4NB,UK,(171) 555-1717,(171) 555-5646
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750


¿Hay nulos en el Dataframe? El resultado debe verse para cada una de las columnas.

In [94]:
df_city.isnull().sum()

CustomerID      0
CompanyName     0
ContactName     0
ContactTitle    0
Address         0
City            0
Region          6
PostalCode      0
Country         0
Phone           0
Fax             1
dtype: int64

Mostrar los principales estadísticos.

In [95]:
df_city.describe()

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
count,7,7,7,7,7,7,1,7,7,7,6
unique,7,7,7,5,7,2,1,7,2,7,6
top,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,WA,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
freq,1,1,1,3,1,6,1,1,6,1,1

In [96]:
df_city.describe(include="object")

C:\Users\fabih\AppData\Local\Temp\ipykernel_27112\4278342600.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_city.describe(include="object")

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
count,7,7,7,7,7,7,1,7,7,7,6
unique,7,7,7,5,7,2,1,7,2,7,6
top,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,WA,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
freq,1,1,1,3,1,6,1,1,6,1,1

In [97]:
df_city.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    7 non-null      str
 1   CompanyName   7 non-null      str
 2   ContactName   7 non-null      str
 3   ContactTitle  7 non-null      str
 4   Address       7 non-null      str
 5   City          7 non-null      str
 6   Region        1 non-null      str
 7   PostalCode    7 non-null      str
 8   Country       7 non-null      str
 9   Phone         7 non-null      str
 10  Fax           6 non-null      str
dtypes: str(11)
memory usage: 748.0 bytes

In [98]:
df_city.columns

Index(['CustomerID', 'CompanyName', 'ContactName', 'ContactTitle', 'Address',
       'City', 'Region', 'PostalCode', 'Country', 'Phone', 'Fax'],
      dtype='str')

In [99]:
col = df_city.columns

In [100]:
col

Index(['CustomerID', 'CompanyName', 'ContactName', 'ContactTitle', 'Address',
       'City', 'Region', 'PostalCode', 'Country', 'Phone', 'Fax'],
      dtype='str')

In [104]:
lista_col = []
for c in col:
    lista_col.append(c)
lista_col

['CustomerID',
 'CompanyName',
 'ContactName',
 'ContactTitle',
 'Address',
 'City',
 'Region',
 'PostalCode',
 'Country',
 'Phone',
 'Fax']

In [105]:
mycursor.description

[('CustomerID', 253, None, None, None, None, 0, 20483, 255),
 ('CompanyName', 253, None, None, None, None, 0, 20489, 255),
 ('ContactName', 253, None, None, None, None, 1, 0, 255),
 ('ContactTitle', 253, None, None, None, None, 1, 0, 255),
 ('Address', 253, None, None, None, None, 1, 0, 255),
 ('City', 253, None, None, None, None, 1, 16392, 255),
 ('Region', 253, None, None, None, None, 1, 16392, 255),
 ('PostalCode', 253, None, None, None, None, 1, 16392, 255),
 ('Country', 253, None, None, None, None, 1, 0, 255),
 ('Phone', 253, None, None, None, None, 1, 0, 255),
 ('Fax', 253, None, None, None, None, 1, 0, 255)]

In [107]:
df_city.columns

Index(['CustomerID', 'CompanyName', 'ContactName', 'ContactTitle', 'Address',
       'City', 'Region', 'PostalCode', 'Country', 'Phone', 'Fax'],
      dtype='str')