En este pair vamos a trabajar la apertura y exploración de archivos. Para finalmente guardar el archivo con un formato diferente.


Hacer las importaciones necesarias para abrir un archivo de tipo csv en Pandas.

In [93]:
import json
import requests
import pandas as pd
import shutil

Abrir el archivo, creando un dataframe. Aseguraros de que no incluye la columna "Unnamed: 0".

In [94]:
df_video = pd.read_csv("videogames.csv", index_col=0)

In [95]:
df_video

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20798,"Enjoy Your Power, Enjoy Your Choice",https://www.imdb.com/title/tt3845606/?ref_=adv...,2014.0,NaN,NaN,NaN,Add a Plot,False,False,False,False,False,False,False,False,True
20799,RedSun2020,https://www.imdb.com/title/tt0790739/?ref_=adv...,2004.0,NaN,NaN,NaN,Joseph gets kidnapped and it's the player's jo...,False,False,False,False,False,False,False,False,True
20800,Shutter,https://www.imdb.com/title/tt5119948/?ref_=adv...,2015.0,NaN,NaN,NaN,A tech support man who uses a drone to investi...,False,False,False,False,False,False,False,False,True
20801,The Music Machine,https://www.imdb.com/title/tt5142082/?ref_=adv...,2015.0,NaN,NaN,NaN,A young teenage girl and the ghost of a dead m...,False,False,False,False,False,False,False,False,True
20802,Cryptic,https://www.imdb.com/title/tt10964974/?ref_=ad...,2020.0,NaN,NaN,NaN,Kidnapped by an insane man and dragged into a ...,False,False,False,False,False,False,False,False,True

Guardar el dataframe en formato Excel y después crear un dataframe con el Excel. ¿El dataframe es similar al que teníais antes?

In [96]:
df_video.to_excel("videogamesexcel.xlsx")

In [97]:
df_excel = pd.read_excel("videogamesexcel.xlsx", index_col=0)

In [98]:
df_excel.shape

(20803, 16)

In [99]:
df_excel.head()

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False

Crear una carpeta llamada Files y guardar el mismo archivo en esa carpeta en formato csv

In [100]:
shutil.copy("videogames.csv", "files")

'files\\videogames.csv'

Copia el archivo personal.json en la carpeta Files.

Abre el fichero json (con el json.load(f)) y haz las modificaciones necesarias para que tenga formato de tabla (Para esto necesitas normalizar los datos con el pd.json_normalize).

In [101]:
with open ("files/personal.json", "r") as f:
    personal = json.load(f)

In [102]:
personal

{'workers': [{'nombre': 'Ana',
   'edad': 34,
   'experiencia': 5,
   'nivel': 'Senior',
   'salario': 50000,
   'mascota': 'gatos'},
  {'nombre': 'Eva',
   'edad': 37,
   'experiencia': 2,
   'nivel': 'Mid',
   'salario': 35000},
  {'nombre': 'Marta',
   'edad': 27,
   'experiencia': 1,
   'nivel': 'Junior',
   'salario': 25000},
  {'nombre': 'Paula',
   'edad': 30,
   'experiencia': 3,
   'nivel': 'Mid',
   'salario': 35000}]}

In [103]:
df_tabla = pd.DataFrame(personal["workers"])

In [104]:
df_tabla

  nombre  edad  experiencia   nivel  salario mascota
0    Ana    34            5  Senior    50000   gatos
1    Eva    37            2     Mid    35000     NaN
2  Marta    27            1  Junior    25000     NaN
3  Paula    30            3     Mid    35000     NaN

In [105]:
df_personal = pd.json_normalize(personal["workers"])

In [106]:
df_personal

  nombre  edad  experiencia   nivel  salario mascota
0    Ana    34            5  Senior    50000   gatos
1    Eva    37            2     Mid    35000     NaN
2  Marta    27            1  Junior    25000     NaN
3  Paula    30            3     Mid    35000     NaN

In [107]:
df_tabla.shape

(4, 6)

Guardar el json modificado y abrirlo en Pandas.¿Cómo queda ahora?

In [118]:
with open ("personal.json", "w") as f:
    json.dump(df_tabla, f)

TypeError: Object of type DataFrame is not JSON serializable

In [119]:
pandas = df_tabla.to_json

In [120]:
pandas

<bound method NDFrame.to_json of   nombre  edad  experiencia   nivel  salario mascota
0    Ana    34            5  Senior    50000   gatos
1    Eva    37            2     Mid    35000     NaN
2  Marta    27            1  Junior    25000     NaN
3  Paula    30            3     Mid    35000     NaN>